select * from KOPO_PRODUCT_VOLUME



-- 사용자 조건 입력받기
SELECT
   REGIONID, PRODUCTGROUP, YEARWEEK
FROM KOPO_PRODUCT_VOLUME
WHERE PRODUCTGROUP = &PRODUCT
OR YEARWEEK = '201544'



-- KOPO_PROMOTION 테이블에서
--STARTWEEK ENDWEEK 2개의
--사용자 변수를 입력 받아 201501, 201503
--사이 데이터를 조회하세요.

select * from KOPO_PROMOTION


SELECT
   *
FROM KOPO_PROMOTION
WHERE 1=1
and targetweek BETWEEN &201501 AND &201503



-- 정렬하기
SELECT
   REGIONID, PRODUCTGROUP, YEARWEEK
FROM KOPO_PRODUCT_VOLUME
WHERE PRODUCTGROUP = 'ST0001'
AND YEARWEEK BETWEEN 201501 AND 201503
ORDER BY YEARWEEK DESC



-- lower (소문자 변환) upper (대문자 변환)
select a.*,
       case when lower (a.gender) = 'not available'
       then 0
       when a.gender = 'male'
       then 1
       else 2 end as sort_order
from kopo_customerdata a
order by sort_order



select distinct gender
from kopo_customerdata




select * from kopo_customerdata


select *
from kopo_product_volume


select 
*
from kopo_product_volume
order by REGIONID,PRODUCTGROUP, YEARWEEK  desc 


-- MINUS (차집합)
SELECT YEARWEEK 
FROM KOPO_PRODUCT_VOLUME
WHERE 1=1
AND PRODUCTGROUP = 'ST0001' 
MINUS 
SELECT YEARWEEK 
FROM KOPO_CHANNEL_RESULT_NEW
WHERE PRODUCTGROUP = 'PG4'



SELECT YEARWEEK 
FROM KOPO_CHANNEL_RESULT_NEW
WHERE PRODUCTGROUP = 'PG4'


SELECT *
FROM KOPO_CHANNEL_RESULT_NEW
WHERE PRODUCTGROUP = 'PG4'




SELECT * FROM KOPO_PRODUCT_VOLUME
WHERE 1=1 
AND PRODUCTGROUP = 'ST0001'
AND YEARWEEK NOT IN (SELECT DISTINCT YEARWEEK FROM KOPO_CHANNEL_RESULT_NEW)



-- 대/소문자 변경하기
SELECT 
   UPPER(PRODUCT) AS CASE1,
   LOWER(PRODUCT) AS CASE2
FROM KOPO_CHANNEL_SEASONALITY_NEW



SELECT * 
FROM KOPO_CHANNEL_SEASONALITY_NEW
WHERE 1=1
AND LOWER(REGIONID) = LOWER(&UI_INPUT1)
AND LOWER(PRODUCT) = LOWER(&UI_INPUT2)


SELECT * FROM KOPO_CHANNEL_SEASONALITY_NEW



-- 컬럼 값 합치기
SELECT 
    CONCAT(REGIONID,CONCAT('_',PRODUCT)) AS KEYCOL1,
    REGIONID||'_'||PRODUCT AS KEYCOL2
FROM KOPO_CHANNEL_SEASONALITY_NEW



KOPO_CUSTOMERDATA에서
KOPO_CUSTOMERCODE를 12자리로 조회하세요
단, 12자리가 안될경우 앞에 ‘*’로 채우세요


SELECT * FROM KOPO_CUSTOMERDATA


SELECT * FROM KOPO_CHANNEL_SEASONALITY_NEW



-- 컬럼 값 채우기
SELECT 
LPAD(PRODUCT, 10,'0')
FROM KOPO_CHANNEL_SEASONALITY_NEW



SELECT A.*,
RPAD(A.CUSTOMERCODE, 12,'0') AS KEY
FROM KOPO_CUSTOMERDATA A


